AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Serverless template for Clinical Notes Summarizer
Globals:
  Function:
    Timeout: 30

Resources:
  SummarizeFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: ClinicalNotesSummarizer-SummarizeFunction
      Runtime: nodejs20.x
      Handler: summarize.handler
      CodeUri: dist/
      MemorySize: 1024
      Policies:
        - AmazonBedrockFullAccess
      Environment:
        Variables:
          MODEL_ID: anthropic.claude-3-sonnet-20240229-v1:0
      Events:
        SummarizeApi:
          Type: Api
          Properties:
            Path: /summarize
            Method: post

Outputs:
  ApiUrl:
    Description: "Invoke URL for API"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/"
